version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: sudo apt-get update && sudo apt-get install build-essential g++
      - run:
          name: run tests
          command: make car-test
